<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\3 - Domain\Impacta.GestaoFrota.Domain\Impacta.GestaoFrota.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AutoMapper\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
