<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\2 - Application\Impacta.GestaoFrota.Application\Impacta.GestaoFrota.Application.csproj" />
    <ProjectReference Include="..\..\4 - Data\Impacta.GestaoFrota.Data\Impacta.GestaoFrota.Data.csproj" />
    <ProjectReference Include="..\..\3 - Domain\Impacta.GestaoFrota.Domain\Impacta.GestaoFrota.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0af62957-18e0-4322-9399-8b97f9a06786</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

</Project>
